---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux
  namespace: flux-system
  labels:
    app: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: flux-system
