---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: helloworld
  labels:
    app: echoserver
    component: echoserver
  annotations:
    flux.weave.works/tag.echoserver: semver:*
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
      component: echoserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echoserver
        component: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      automountServiceAccountToken: false
